config/routes.rb
Rails.application.routes.draw do
  resources :postacs
  resources :klasas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  get "/about" => "home#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klasa.rb
class Klasa < ApplicationRecord
has_many :postacs
end

app/models/postac.rb
class Postac < ApplicationRecord
  belongs_to :klasa
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end


end

app/controllers/klasas_controller.rb
class KlasasController < ApplicationController
  before_action :set_klasa, only: [:show, :edit, :update, :destroy]

  # GET /klasas
  # GET /klasas.json
  def index
    @klasas = Klasa.all
  end

  # GET /klasas/1
  # GET /klasas/1.json
  def show
  end

  # GET /klasas/new
  def new
    @klasa = Klasa.new
  end

  # GET /klasas/1/edit
  def edit
  end

  # POST /klasas
  # POST /klasas.json
  def create
    @klasa = Klasa.new(klasa_params)

    respond_to do |format|
      if @klasa.save
        format.html { redirect_to @klasa, notice: 'Klasa was successfully created.' }
        format.json { render :show, status: :created, location: @klasa }
      else
        format.html { render :new }
        format.json { render json: @klasa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klasas/1
  # PATCH/PUT /klasas/1.json
  def update
    respond_to do |format|
      if @klasa.update(klasa_params)
        format.html { redirect_to @klasa, notice: 'Klasa was successfully updated.' }
        format.json { render :show, status: :ok, location: @klasa }
      else
        format.html { render :edit }
        format.json { render json: @klasa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klasas/1
  # DELETE /klasas/1.json
  def destroy
    @klasa.destroy
    respond_to do |format|
      format.html { redirect_to klasas_url, notice: 'Klasa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klasa
      @klasa = Klasa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klasa_params
      params.require(:klasa).permit(:name, :description, :specialatk)
    end
end

app/controllers/postacs_controller.rb
class PostacsController < ApplicationController
  before_action :set_postac, only: [:show, :edit, :update, :destroy]

  # GET /postacs
  # GET /postacs.json
  def index
    @postacs = Postac.all
  end

  # GET /postacs/1
  # GET /postacs/1.json
  def show
  end

  # GET /postacs/new
  def new
    @postac = Postac.new
  end

  # GET /postacs/1/edit
  def edit
  end

  # POST /postacs
  # POST /postacs.json
  def create
    @postac = Postac.new(postac_params)

    respond_to do |format|
      if @postac.save
        format.html { redirect_to @postac, notice: 'Postac was successfully created.' }
        format.json { render :show, status: :created, location: @postac }
      else
        format.html { render :new }
        format.json { render json: @postac.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postacs/1
  # PATCH/PUT /postacs/1.json
  def update
    respond_to do |format|
      if @postac.update(postac_params)
        format.html { redirect_to @postac, notice: 'Postac was successfully updated.' }
        format.json { render :show, status: :ok, location: @postac }
      else
        format.html { render :edit }
        format.json { render json: @postac.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postacs/1
  # DELETE /postacs/1.json
  def destroy
    @postac.destroy
    respond_to do |format|
      format.html { redirect_to postacs_url, notice: 'Postac was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postac
      @postac = Postac.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postac_params
      params.require(:postac).permit(:name, :lvl, :maglvl, :atk, :def, :magic, :speed, :klasa_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/klasas_helper.rb
module KlasasHelper
end

app/helpers/postacs_helper.rb
module PostacsHelper
end

app/views/home/_header.html.erb
<div class="container">
<%=link_to 'Strona glowna',root_path, class:"btn btn-success" %> 
<%=link_to 'About',about_path, class:"btn btn-success" %>
</div>

app/views/home/about.html.erb
<body class="bg-warning">
<h1> Patryk Mioduszewski - strona o klasach postaci w grach komputerowych </h1>
</body>

app/views/home/index.html.erb
<body class="bg-warning">
<h1> Zaliczenie</h1>
</body>


<%=link_to 'Klasy postaci',klasas_path, class:"btn btn-success" %>
<%=link_to 'Postacie graczy',postacs_path, class:"btn btn-success" %>

app/views/klasas/_form.html.erb
<%= form_with(model: klasa, local: true) do |form| %>
  <% if klasa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(klasa.errors.count, "error") %> prohibited this klasa from being saved:</h2>

      <ul>
      <% klasa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :klasa_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :klasa_description %>
  </div>

  <div class="field">
    <%= form.label :specialatk %>
    <%= form.text_field :specialatk, id: :klasa_specialatk %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/klasas/edit.html.erb
<h1>Editing Klasa</h1>

<%= render 'form', klasa: @klasa %>

<%= link_to 'Show', @klasa %> |
<%= link_to 'Back', klasas_path %>

app/views/klasas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Klasas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Specialatk</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @klasas.each do |klasa| %>
      <tr>
        <td><%= klasa.name %></td>
        <td><%= klasa.description %></td>
        <td><%= klasa.specialatk %></td>
        <td><%= link_to 'Show', klasa %></td>
        <td><%= link_to 'Edit', edit_klasa_path(klasa) %></td>
        <td><%= link_to 'Destroy', klasa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Klasa', new_klasa_path %>

app/views/klasas/new.html.erb
<h1>New Klasa</h1>

<%= render 'form', klasa: @klasa %>

<%= link_to 'Back', klasas_path %>

app/views/klasas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @klasa.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @klasa.description %>
</p>

<p>
  <strong>Specialatk:</strong>
  <%= @klasa.specialatk %>
</p>

<%= link_to 'Edit', edit_klasa_path(@klasa) %> |
<%= link_to 'Back', klasas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magowie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
	<%=render "home/header"%>
    <div class="container">
    <%= yield %>
  </body>
</html>

app/views/postacs/_form.html.erb
<%= form_with(model: postac, local: true) do |form| %>
  <% if postac.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(postac.errors.count, "error") %> prohibited this postac from being saved:</h2>

      <ul>
      <% postac.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :postac_name %>
  </div>

  <div class="field">
    <%= form.label :lvl %>
    <%= form.number_field :lvl, id: :postac_lvl %>
  </div>

  <div class="field">
    <%= form.label :maglvl %>
    <%= form.number_field :maglvl, id: :postac_maglvl %>
  </div>

  <div class="field">
    <%= form.label :atk %>
    <%= form.number_field :atk, id: :postac_atk %>
  </div>

  <div class="field">
    <%= form.label :def %>
    <%= form.number_field :def, id: :postac_def %>
  </div>

  <div class="field">
    <%= form.label :magic %>
    <%= form.number_field :magic, id: :postac_magic %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed, id: :postac_speed %>
  </div>

	<div class="field">
    <%= form.label :Klasa_id %>
    <%= form.collection_select :klasa_id, Klasa.order(:name), :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/postacs/edit.html.erb
<h1>Editing Postac</h1>

<%= render 'form', postac: @postac %>

<%= link_to 'Show', @postac %> |
<%= link_to 'Back', postacs_path %>

app/views/postacs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postacs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lvl</th>
      <th>Maglvl</th>
      <th>Atk</th>
      <th>Def</th>
      <th>Magic</th>
      <th>Speed</th>
      <th>Klasa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postacs.each do |postac| %>
      <tr>
        <td><%= postac.name %></td>
        <td><%= postac.lvl %></td>
        <td><%= postac.maglvl %></td>
        <td><%= postac.atk %></td>
        <td><%= postac.def %></td>
        <td><%= postac.magic %></td>
        <td><%= postac.speed %></td>
        <td><%= postac.klasa.name %></td>
        <td><%= link_to 'Show', postac %></td>
        <td><%= link_to 'Edit', edit_postac_path(postac) %></td>
        <td><%= link_to 'Destroy', postac, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postac', new_postac_path %>

app/views/postacs/new.html.erb
<h1>New Postac</h1>

<%= render 'form', postac: @postac %>

<%= link_to 'Back', postacs_path %>

app/views/postacs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @postac.name %>
</p>

<p>
  <strong>Lvl:</strong>
  <%= @postac.lvl %>
</p>

<p>
  <strong>Maglvl:</strong>
  <%= @postac.maglvl %>
</p>

<p>
  <strong>Atk:</strong>
  <%= @postac.atk %>
</p>

<p>
  <strong>Def:</strong>
  <%= @postac.def %>
</p>

<p>
  <strong>Magic:</strong>
  <%= @postac.magic %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @postac.speed %>
</p>

<p>
  <strong>Klasa:</strong>
  <%= @postac.klasa %>
</p>

<%= link_to 'Edit', edit_postac_path(@postac) %> |
<%= link_to 'Back', postacs_path %>